from setuptools import setup, find_packages

setup(
    name='pegasus',
    version='0.1.0',
    description='A lightweight terminal agent framework for long-running modular agents',
    url='https://github.com/asuzukosi/pegasus',
    author='Asuzu Kosi',
    author_email='keloasuzu@yahoo.com',
    license='BSD 2-clause',
    packages=find_packages(),
    install_requires=[
        'anthropic',
        'click',
        'openai',
        'retry',
        'rich',
        'tiktoken',
        'platformdirs',
        'tomli',
        'duckduckgo-search',
        'ddgs',
        'fastmcp',
        'pydantic',
        'python-dotenv',
        'markdownify',
        'beautifulsoup4',
        'lxml',
        'requests',
        'pytest-asyncio',
        'diskcache',
        'pillow',
        'imageio-ffmpeg',
        'fake-useragent',
        'PyJWT',
        'pyyaml'
    ],
    entry_points={
        'console_scripts': [
            'pegasus-cli=pegasus.cli.cli:run_cli',
        ],
    },
    python_requires='>=3.9',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
    ],
)
